/**
 * 内置精选 prompt（首次使用时落地为初始数据，之后用户可改/删/导入覆盖）。
 * 选取覆盖不同分类与技巧，体现业界常见的 prompt 工程范式：清晰角色、
 * 明确任务、结构化输出、给示例（few-shot）、要求分步思考（CoT）、设边界。
 */

const T = Date.UTC(2026, 0, 1);

export const SEEDS = [
  {
    id: 'seed_code_review',
    title: '资深代码评审员',
    summary: '以资深工程师视角审阅 diff，按严重度分级给出可执行修改建议。',
    category: 'coding',
    tags: ['code-review', 'engineering', 'quality'],
    models: ['Claude', 'GPT'],
    techniques: ['role', 'structured-output', 'guardrails'],
    system:
      '你是一名有 10 年经验的资深软件工程师，负责代码评审。你重视正确性、可读性与可维护性，反馈具体、克制、可执行，绝不无依据地猜测。',
    content:
      '请评审下面的代码改动。\n\n<diff>\n{{diff}}\n</diff>\n\n按以下要求输出：\n1. 先用一句话总结改动意图。\n2. 列出问题，每条标注严重度（阻断 / 重要 / 次要 / 建议），给出所在位置与具体修改方案。\n3. 仅基于给定 diff，不臆测未展示的代码；信息不足时明确指出需要补充什么。\n4. 没有问题就明确说「未发现明显问题」。',
    exampleInput: 'diff = 一段新增了未处理 null 分支的 JS 函数',
    exampleOutput: '意图：新增用户校验。\n- [重要] L12：data 可能为 null，调用 .name 会抛错，建议先判空…',
    notes: '把代码放进 <diff> 标签可降低指令与数据混淆。要求标注严重度便于排优先级。',
    source: '改编自常见代码评审最佳实践',
    license: 'CC0',
    version: '1.0.0',
    favorite: true,
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'seed_summarize',
    title: '结构化摘要器',
    summary: '把长文压缩为面向特定读者的要点摘要，控制长度与口吻。',
    category: 'writing',
    tags: ['summary', 'tldr'],
    models: ['Any'],
    techniques: ['structured-output', 'guardrails'],
    system: '你是一名擅长把复杂内容讲清楚的编辑。',
    content:
      '为「{{audience}}」读者把下面的文本总结成 {{count}} 条要点，每条不超过 25 字，只保留对该读者最重要的信息，不要添加原文没有的内容。\n\n文本：\n"""\n{{text}}\n"""',
    exampleInput: 'audience=产品经理, count=3, text=一篇技术架构长文',
    exampleOutput: '• 新架构把延迟降低约 40%\n• 迁移分两期，对现有 API 兼容\n• 主要风险在数据回填',
    notes: '用三引号包裹原文、显式禁止编造，是抑制幻觉的常用手段。',
    source: '通用摘要模式',
    license: 'CC0',
    version: '1.0.0',
    favorite: false,
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'seed_cot_math',
    title: '分步推理求解（CoT）',
    summary: '要求模型先分步推理再给结论，提升复杂问题准确率。',
    category: 'analysis',
    tags: ['reasoning', 'math', 'cot'],
    models: ['Any'],
    techniques: ['chain-of-thought', 'structured-output'],
    system: '你是严谨的解题助手。',
    content:
      '请解决下面的问题。\n\n问题：{{question}}\n\n要求：\n1. 在 <thinking> 标签内一步步推理，列出关键假设与中间结果。\n2. 在 <answer> 标签内只给出最终答案，简洁明确。\n3. 如条件不足以得出唯一答案，请在 <answer> 中说明缺少什么。',
    exampleInput: 'question=一个两步的应用题',
    exampleOutput: '<thinking>设…，则…</thinking>\n<answer>42</answer>',
    notes: '把「思考」与「答案」分到不同标签，既保留推理又方便程序只取结论。',
    source: 'Chain-of-Thought 提示范式',
    license: 'CC0',
    version: '1.0.0',
    favorite: true,
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'seed_extract_json',
    title: 'JSON 信息抽取（Few-shot）',
    summary: '从自由文本抽取结构化字段，用示例约束输出格式，仅返回 JSON。',
    category: 'extraction',
    tags: ['json', 'parsing', 'structured'],
    models: ['Claude', 'GPT', 'Gemini'],
    techniques: ['few-shot', 'structured-output', 'guardrails'],
    system: '你是信息抽取引擎，只输出合法 JSON，不要任何解释或代码块标记。',
    content:
      '从文本中抽取字段：name、email、company。缺失填 null。\n\n示例：\n输入：「我是来自 Acme 的张三，邮箱 zhangsan@acme.com」\n输出：{"name":"张三","email":"zhangsan@acme.com","company":"Acme"}\n\n现在处理：\n输入：「{{text}}」\n输出：',
    exampleInput: 'text=「李雷，bytedance，没有留邮箱」',
    exampleOutput: '{"name":"李雷","email":null,"company":"bytedance"}',
    notes: '给 1~2 个示例（few-shot）能显著稳定输出格式；显式禁止代码块包裹避免解析失败。',
    source: 'Few-shot 抽取模式',
    license: 'CC0',
    version: '1.0.0',
    favorite: false,
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'seed_agent_react',
    title: 'ReAct 工具调用代理',
    summary: '让模型在「思考—行动—观察」循环中使用工具，适合 agent 场景。',
    category: 'agent',
    tags: ['agent', 'tools', 'react'],
    models: ['Claude', 'GPT'],
    techniques: ['react', 'role', 'guardrails'],
    system:
      '你是一个能调用工具的助手。可用工具：search(query)、calculator(expr)。每一步只做一件事，严格按格式输出。',
    content:
      '目标：{{goal}}\n\n按如下循环推进，直到能回答：\nThought: 你的推理\nAction: 工具名(参数)\nObservation: （系统会填入工具结果）\n…重复…\nFinal Answer: 最终回答\n\n规则：无需工具时直接给 Final Answer；不要编造 Observation。',
    exampleInput: 'goal=「北京到上海高铁最快多久，再乘以 2 是多少小时」',
    exampleOutput: 'Thought: 先查时长\nAction: search("北京 上海 高铁 最快")\n…',
    notes: 'ReAct 把推理与工具调用交错，便于挂接真实工具执行器。务必禁止模型自行编造 Observation。',
    source: 'ReAct: Reasoning + Acting 范式',
    license: 'CC0',
    version: '1.0.0',
    favorite: false,
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'seed_socratic',
    title: '苏格拉底式辅导老师',
    summary: '不直接给答案，用提问引导学习者自己推导，适合教学。',
    category: 'education',
    tags: ['tutor', 'socratic', 'learning'],
    models: ['Any'],
    techniques: ['role', 'guardrails'],
    system:
      '你是一位耐心的导师，采用苏格拉底式教学：通过提问启发学生思考，而不是直接给出答案。每次只问一个问题，依据学生回答调整难度。',
    content:
      '学生正在学习「{{topic}}」，当前水平：{{level}}。\n请开始一段引导式对话：先用一个开放问题了解其已有理解，再逐步深入。只有当学生明显卡住时才给出最小提示，绝不直接说出完整答案。',
    exampleInput: 'topic=递归, level=初学者',
    exampleOutput: '我们先从一个小问题开始：你觉得「一个函数调用它自己」会发生什么？',
    notes: '通过角色与硬约束（不直接给答案）塑造教学行为。',
    source: '苏格拉底式教学模式',
    license: 'CC0',
    version: '1.0.0',
    favorite: false,
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'seed_rewrite_tone',
    title: '语气改写器',
    summary: '在保持原意的前提下，把文本改写成指定语气与受众。',
    category: 'writing',
    tags: ['rewrite', 'tone', 'copywriting'],
    models: ['Any'],
    techniques: ['zero-shot', 'guardrails'],
    system: '你是专业文案编辑。',
    content:
      '把下面的文本改写为「{{tone}}」语气，面向「{{audience}}」。保持原意与关键信息不变，不夸大、不杜撰事实。只输出改写后的文本。\n\n原文：\n{{text}}',
    exampleInput: 'tone=亲切口语, audience=新用户, text=一段生硬的产品说明',
    exampleOutput: '（改写后的亲切版本…）',
    notes: '把语气、受众参数化，便于一稿多投；强调不杜撰避免改写时加料。',
    source: '通用改写模式',
    license: 'CC0',
    version: '1.0.0',
    favorite: false,
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'seed_brainstorm',
    title: '发散点子生成器',
    summary: '围绕主题产出多样化、可执行的创意，并附一句评估。',
    category: 'creative',
    tags: ['brainstorm', 'ideation'],
    models: ['Any'],
    techniques: ['role', 'structured-output'],
    system: '你是富有创意又务实的策划，点子既新颖又能落地。',
    content:
      '围绕主题「{{topic}}」生成 {{count}} 个互不重复的点子。约束：{{constraints}}。\n每个点子用一行：标题 — 一句话说明 — 落地难度（低/中/高）。避免雷同与套话。',
    exampleInput: 'topic=提升 App 次日留存, count=5, constraints=不增加预算',
    exampleOutput: '1. 首日任务卡 — 引导完成核心动作 — 低\n…',
    notes: '要求「互不重复 + 标注难度」能拉开点子质量、便于筛选。',
    source: '头脑风暴模式',
    license: 'CC0',
    version: '1.0.0',
    favorite: false,
    createdAt: T,
    updatedAt: T,
  },
];
